apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "5684"
      port: 5684
      targetPort: 5684
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
