---
services:
  core:
    container_name: ip-core
    image: ghcr.io/timmo001/ip-core/amd64:edge
    restart: unless-stopped
    ports:
      - target: 5686
        published: 5686
        protocol: tcp
    volumes:
      - type: volume
        source: ip-data
        target: /root/.local/share/ip-data
  backend:
    container_name: ip-backend
    image: ghcr.io/timmo001/ip-backend/amd64:edge
    restart: unless-stopped
    environment:
      CORE_HOST: ip-core
    ports:
      - target: 5684
        published: 5684
        protocol: tcp
    volumes:
      - type: volume
        source: ip-data
        target: /root/.local/share/ip-data
  frontend:
    container_name: ip-frotend
    image: ghcr.io/timmo001/ip-frontend/amd64:edge
    restart: unless-stopped
    ports:
      - target: 8080
        published: 8080
        protocol: tcp

volumes:
  ip-data: {}
