apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: ghcr.io/timmo001/ip-frontend/amd64:edge
          name: ip-frotend
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
