apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: core
  name: core
spec:
  ports:
    - name: "5686"
      port: 5686
      targetPort: 5686
  selector:
    io.kompose.service: core
status:
  loadBalancer: {}
