apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: core
  name: core
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: core
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: core
    spec:
      containers:
        - image: ghcr.io/timmo001/ip-core/amd64:edge
          name: ip-core
          ports:
            - containerPort: 5686
          resources: {}
          volumeMounts:
            - mountPath: /root/.local/share/ip-data
              name: ip-data
      restartPolicy: Always
      volumes:
        - name: ip-data
          persistentVolumeClaim:
            claimName: ip-data
status: {}
